/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Multiplayer;

import JPuyo.*;
import java.awt.*;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author eugeniolr
 */
public class GameMultiWindow extends javax.swing.JFrame {
    
    /**
     *
     */
    private final ArrayList<BoardPanel> boardPanels;
    private final ArrayList<GameMultiLoop> gameLoops;
    private final JFrame parentWindow;
            
    /**
     * Creates new form GameWindow
     * @param parentWindow
     * @param nPlayers
     */
    public GameMultiWindow(JFrame parentWindow, int nPlayers) {
        initComponents();
        this.parentWindow = parentWindow;
        this.boardPanels = new ArrayList<>();
        this.gameLoops = new ArrayList<>();
        GridLayout gl = new GridLayout(1,nPlayers);
        gl.setHgap(-100);
        this.mainPanel.setLayout(gl);
        prepareGame(nPlayers);
        
        setLocationRelativeTo(parentWindow);
        setResizable(false);
    }
    
    /**
     *
     * @param nPlayers
     */
    public final void prepareGame(int nPlayers){
        new ImageLoader();
        for(int i = 0; i < nPlayers; i++){
            this.boardPanels.add(new BoardPanel(8, 12));
        }
        int w = 0, h = 0;
        for(BoardPanel bp : boardPanels){
            w += bp.getWidth();
        }
        h += boardPanels.get(0).getHeight();
        w += 100;
        this.getContentPane().setPreferredSize(new Dimension(w, h));
        this.pack();
        
        int i = 0;
        for(BoardPanel bp : boardPanels){
            this.mainPanel.add(bp);
            GameMultiLoop gl = new GameMultiLoop(this, i);
            gl.start();
            i++;
        }
        
        setLocationRelativeTo(null);
    }
    
    /**
     *
     * @param id
     * @param score
     * @throws InterruptedException
     */
    public void attackOponents(int id, long score) throws InterruptedException{
        for(GameMultiLoop gml : gameLoops){
            if(gml.getPlayer() != id){
                gml.oponentAttack((int)(score/2000));
            }
        }
    }
    /**
     *
     * @return
     */
    public ArrayList<BoardPanel> getBoardPanel(){
        return this.boardPanels;
    }
    
    /**
     *
     * @return
     */
    public JPanel getMainFrame() {
        return this.mainPanel;
    }
    
    /**
     * Goes to the main menu
     */
    public void exitToMenu(){
        this.setVisible(false);
        parentWindow.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(15, 15, 15));
        mainPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
