/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DuoGame;

import JPuyo.*;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author eugeniolr
 */
public class GameWindow extends javax.swing.JFrame {
    
    /**
     *
     */
    private BoardPanel boardPanel;
    private final JFrame parentWindow;
            
    /**
     * Creates new form GameWindow
     * @param parentWindow
     * @param mode
     */
    public GameWindow(JFrame parentWindow, int mode) {
        initComponents();
        this.parentWindow = parentWindow;
        prepareGame(mode);
        setLocationRelativeTo(parentWindow);
        setResizable(false);
    }
    
    /**
     *
     * @param mode
     */
    public void prepareGame(int mode){
        new ImageLoader();
        this.boardPanel = new BoardPanel(8, 12);
        this.getContentPane().setPreferredSize(new Dimension(boardPanel.getWidth() + 100, boardPanel.getHeight()));
        this.pack();
        GameLoop gl = new GameLoop(this, mode);
        this.mainPanel.add(boardPanel);
        gl.start();
        setLocationRelativeTo(null);
    }
    
    /**
     *
     * @return
     */
    public javax.swing.JLabel getPointsLabel(){
        return this.pointsLabel;
    }
    
    /**
     *
     * @return
     */
    public javax.swing.JLabel getupdateText(){
        return this.updateText;
    }
    
    /**
     *
     * @return
     */
    public javax.swing.JLabel getLevelLabel(){
        return this.levelLabel;
    }
    
    /**
     *
     * @return
     */
    public BoardPanel getBoardPanel(){
        return this.boardPanel;
    }
    
    /**
     *
     * @return
     */
    public JPanel getMainFrame() {
        return this.mainPanel;
    }
    
    /**
     * goes back to the main menu
     */
    public void exitToMenu(){
        this.setVisible(false);
        parentWindow.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        levelLabel = new javax.swing.JLabel();
        pointsLabel = new javax.swing.JLabel();
        updateText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(15, 15, 15));

        levelLabel.setForeground(new java.awt.Color(255, 255, 255));
        levelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        levelLabel.setText("Level:0");

        pointsLabel.setForeground(new java.awt.Color(255, 255, 255));
        pointsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pointsLabel.setText("35 points");

        updateText.setForeground(new java.awt.Color(255, 255, 255));
        updateText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap(227, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pointsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(levelLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(pointsLabel)
                .addGap(18, 18, 18)
                .addComponent(levelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateText, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel levelLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel pointsLabel;
    private javax.swing.JLabel updateText;
    // End of variables declaration//GEN-END:variables
}
